Repository cloudposse/terraform-aws-ec2-bastion-server, pull requests merged in 2024-05, with the labels that each got.

#229 Update GitHub workflows
  .github/workflows/feature-branch.yml
  .github/workflows/release-branch.yml
  .github/workflows/scheduled.yml
Labels: auto-update, no-release, migration

#231 Update GitHub Workflows to Fix ReviewDog TFLint Action
  .github/workflows/feature-branch.yml
Labels: auto-update, no-release, migration

#232 ci: update test modules
  examples/complete/main.tf
  examples/complete/versions.tf
Labels: no-release

#233 Fix legacy splat expressions
  main.tf
  outputs.tf
Labels: no-release

#230 Remove deprecated argument "vpc"
  main.tf
Labels: patch

#235 Update GitHub Workflows to use shared workflows from '.github' repo
  .github/workflows/branch.yml
  .github/workflows/chatops.yml
  .github/workflows/feature-branch.yml
  .github/workflows/release-published.yml
  .github/workflows/release.yml
  .github/workflows/scheduled.yml
Labels: auto-update, no-release, migration
